config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  post 'events' => 'events#create'

  resources :responses, except: [:edit, :update]

  root 'responses#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  session    :uuid
#  view       :uuid
#  time       :datetime
#  question   :string
#  kind       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  campaign   :string
#
# Indexes
#
#  index_events_on_session  (session)
#  index_events_on_view     (view)
#

class Event < ApplicationRecord

  validates :session, presence: true
  validates :view, presence: true
  validates :time, presence: true
  validates :kind, presence: true

end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  session    :uuid
#  view       :uuid
#  answers    :json
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  email      :string
#  name       :string
#  campaign   :string
#
# Indexes
#
#  index_responses_on_session  (session)
#  index_responses_on_view     (view)
#

class Response < ApplicationRecord

  validates :session, presence: true
  validates :view, presence: true
  validates :answers, presence: true
  validates :email, presence: true

  after_commit :create_event, on: :create

  def create_event
    Event.create(
             session: self.session,
             view: self.view,
             time: DateTime.now,
             kind: 'success'
    )
  end

  def self.to_csv
    csv = ['id', 'email', 'name', 'campaign', 'created_at', *QUESTIONS.map{|_key, q| q[:title].gsub(',', '')}].join(',') + "\n"

    all.each do |response|
      csv += [
          response.id,
          response.email,
          response.name,
          response.campaign,
          response.created_at,
          *QUESTIONS.map{|key, _q| response.answers[key]}
      ].join(',') + "\n"
    end

    csv
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  admin                  :boolean          default(FALSE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_analytics_ids

  def set_analytics_ids
    if session[:session_uuid].present?
      @session_id = session[:session_uuid]
    else
      session[:session_uuid] = @session_id = SecureRandom.uuid
    end

    if params[:campaign].present?
      session[:campaign] = @campaign = params[:campaign]
    elsif session[:campaign].present?
      @campaign = session[:campaign]
    end

    @view_id = SecureRandom.uuid
  end

  def requires_admin
    redirect_to('/users/sign_in') unless current_user && current_user.admin
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def create

    @event = Event.new(event_params)

    if @event.save
      render json: {event: @event}, status: :created
    else
      render json: @response.errors, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:session, :view, :time, :question, :kind, :campaign)
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]
  before_action :set_questions, only: [:new, :edit, :update, :create]

  before_action :requires_admin, only: [:index, :edit, :update, :show]

  # GET /responses
  # GET /responses.json
  def index
    session[:session_uuid] = nil
    @responses = Response.order('created_at')
    @page_views = Event.where(kind: 'pageLoad').count

    @by_campaign = {}
    @responses.each do |response|
      @by_campaign[response.campaign] = {
          count: 0,
          first_time: 0
      } if @by_campaign[response.campaign].nil?

      @by_campaign[response.campaign][:count] += 1
    end

    @by_campaign.keys.each do |campaign|
      @by_campaign[campaign][:page_views] = Event.where(kind: 'pageLoad', campaign: campaign).count
    end

    respond_to do |format|
      format.html
      format.csv { send_data @responses.to_csv }
    end

  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    puts response_params
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        session[:session_uuid] = nil

        format.html { render :thanks }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_response
    @response = Response.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def response_params
    params.require(:response).permit(:session, :view, :email, :name, :campaign).to_h.tap do |parameters|
      parameters[:answers] = {}

      QUESTIONS.each do |key, opts|
        parameters[:answers][key] = params[:response][:answers][key]

        if opts[:type] == 'rank'
          parameters[:answers][key] = JSON(parameters[:answers][key])
        end
      end
    end
  end

  def set_questions
    @questions = QUESTIONS
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/form_helper.rb
module FormHelper

  def question(opts)

    render partial: 'question', locals: opts

  end

end

app/helpers/responses_helper.rb
module ResponsesHelper

  def question(opts)

    if opts[:outside_answer]
      opts[:fixed_name] = "response[#{ opts[:name] }]"
    else
      opts[:fixed_name] = "response[answers][#{ opts[:name] }]"
    end

    opts[:type] = 'textarea' if opts[:type].blank?

    opts[:id] = "question-#{(0...16).map { ('a'..'z').to_a[rand(26)] }.join}"

    render partial: 'question', locals: {opts: opts}
  end

end

app/views/responses/_form.html.erb
<% if @campaign.to_s == 'sustainableimpact' %>
  <p>
    At the Straubel Foundation, we aim to drive sustainability through science, engineering, and social innovation. If you are an emerging leader dedicated to creating a sustainable impact in your community, please fill out our brief (10-minute) pre-application here by midnight on Sunday, March 4th. Completing the pre-application will highlight your application and prioritize its review. Your input will also help evolve our awards’ benefits.
  </p>
<% else %>
  <p>
    At the Straubel Foundation, we aim to empower leaders and maximize the impact of their work. If you are an emerging leader dedicated to making an impact in your community, please fill out our brief (10-minute) pre-application here by midnight on Sunday, March 4th. Completing the pre-application will highlight your application and prioritize its review. Your input will also help evolve our awards’ benefits.
  </p>
<% end %>

<%= form_with(model: response, local: true) do |form| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
        <% response.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= question title: 'Name', name: 'name', outside_answer: true, type: 'text' %>

  <%= question title: 'Email', name: 'email', outside_answer: true, type: 'text', required: true %>

  <% @questions.each do |_name, question| %>
    <% if question[:campaigns].blank? || question[:campaigns].include?(@campaign) %>
      <%= question question %>
    <% end %>
  <% end %>

  <input type="hidden" name="response[session]" value="<%= @session_id %>">
  <input type="hidden" name="response[view]" value="<%= @view_id %>">

  <% if @campaign.present? %>
    <input type="hidden" name="response[campaign]" value="<%= @campaign %>">
  <% end %>

  <div class="actions">
    <%= form.submit 'Submit', class: 'sqs-donate-button sqs-suppress-edit-mode sqs-system-button sqs-editable-button', id: 'submit-button' %>
  </div>
<% end %>

<script>
    document.getElementById('submit-button').addEventListener('click', function(){
        createEvent({
            kind: 'submit',
            question: name
        });
    })
</script>

app/views/responses/_question.html.erb
<div class="question" id="<%= opts[:id] %>">
  <h2><%= opts[:title] %></h2>
  <% if opts[:description] %>
    <%= opts[:description] %>
  <% end %>

  <% if opts[:type] == 'textarea' %>
    <textarea name="<%= opts[:fixed_name] %>"></textarea>
  <% elsif opts[:type] == 'rank' %>
    <input type="hidden" name="<%= opts[:fixed_name] %>" class="result">

    <ul class="rank">
      <% opts[:options].each do |option| %>
        <li><%= option %></li>
      <% end %>

      <% if opts[:include_other] %>
        <li class="other">Other: <input type="text"></li>
      <% end %>
    </ul>
  <% elsif opts[:type] == 'scale' %>

    <ul class="scale">
      <% opts[:options].each do |option| %>
        <li>
          <label>
            <%= option %>

            <select name="<%= opts[:fixed_name] %>[<%= option %>]">
              <option value="1">1 - Not interested</option>
              <option value="2">2 - Low interest</option>
              <option value="3">3 - Medium interest</option>
              <option value="4">4 - Strong interest</option>
              <option value="5">5 - Top priority</option>
            </select>
          </label>
        </li>
      <% end %>

      <% if opts[:include_other] %>
        <li class="other">
          <%= opts[:other_label] || 'Other:' %> <input type="text" name="<%= opts[:fixed_name] %>[other]">
        </li>
      <% end %>
    </ul>
  <% elsif opts[:type] == 'checkbox' %>
    <% opts[:options].each do |option| %>
      <label><input type="checkbox" name="<%= opts[:fixed_name] %>[]" value="<%= option %>"> <%= option %></label> <br/>
    <% end %>

    <% if opts[:include_other] %>
      <label class="other"><input type="checkbox" name="<%= opts[:fixed_name] %>[]"> Other: <input type="text"></label> <br/>
    <% end %>
  <% else %>
    <input type="<%= opts[:type] %>" name="<%= opts[:fixed_name] %>">
  <% end %>

</div>

<script>
    document.addEventListener('turbolinks:load', function () {
        initializeQuestion(<%= sanitize opts.to_json %>);
    });
</script>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses</h1>

<h2>
  <%= @responses.count %> responses total / <%= @page_views %> page views
</h2>

<table>
  <thead>
  <tr>
    <th>Campaign</th>
    <th>Name</th>
    <th>Email</th>
    <th>Date</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @responses.each do |response| %>
    <tr>
      <td><%= response.campaign %></td>
      <td><%= response.name %></td>
      <td><%= response.email %></td>
      <td><%= response.created_at.to_formatted_s(:short) %></td>
      <td><%= link_to 'Show', response %></td>
      <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<h2>
  By campaign
</h2>

<table>
  <thead>
  <tr>
    <th>Campaign</th>
    <th>Count</th>
    <th>Page views</th>
  </tr>
  </thead>

  <tbody>
  <% @by_campaign.each do |campaign, details| %>
    <tr>
      <td>
        <%= campaign %>
      </td>
      <td>
        <%= details[:count] %>
      </td>
      <td>
        <%= details[:page_views] %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/responses/new.html.erb
<h1>Straubel Leadership Awards pre-application</h1>

<%= render 'form', response: @response %>

<script>
  createEvent({
      kind: 'pageLoad'
  });
</script>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Session:</strong>
  <%= @response.session %>
</p>

<p>
  <strong>View:</strong>
  <%= @response.view %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @response.campaign %>
</p>

<p>
  <strong>Date:</strong>
  <%= @response.created_at.to_formatted_s(:long) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @response.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @response.email %>
</p>

<p>
  <strong>Answers:</strong>

<table>
  <% @response.answers.each do |key, value| %>
    <tr>
      <th><%= key %></th>
      <td>
        <% if value.is_a? Array %>
          <ul>
            <% value.each do |item| %>
              <li style="text-align: left">
                <%= item %>
              </li>
            <% end %>
          </ul>
        <% elsif value.is_a? Hash %>
          <ul>
            <% value.each do |key, value| %>
              <li style="text-align: left">
                <b><%= key %></b>: <%= value %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <%= value %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
</p>

app/views/responses/thanks.html.erb
<h1>Thanks for submitting your pre-application</h1>
You'll have top priority when the main application is released -- keep your eyes peeled for the email!